
services:
  frontend:
    image: ghcr.io/hikka-io/hikka-next:latest
    restart: always
    ports:
      - 127.0.0.1:3000:3000
    depends_on:
      - backend

  backend:
    image: ghcr.io/hikka-io/hikka:latest
    restart: always
    volumes:
      - ./conf/backend/settings.toml:/project/settings.toml
    ports:
      - 127.0.0.1:8001-8004:8000
    deploy:
      replicas: 4
    depends_on:
      - sync

  sync:
    image: ghcr.io/hikka-io/hikka:latest
    command: sh -c "alembic upgrade head && python sync.py"
    restart: always
    volumes:
      - ./conf/backend/settings.toml:/project/settings.toml
      - ./sitemap:/project/sitemap
    depends_on:
      - postgres
      - meilisearch

  postgres:
    image: postgres:16.3-alpine3.20
    restart: always
    shm_size: 2gb
    environment:
      POSTGRES_DB: hikka
      POSTGRES_USER: ${PG_USER:-hikka_admin}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-hikka_pwd}
    volumes:
      - ./data/pg_data:/var/lib/postgresql/data
      - ./conf/postgres/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      #- ./hikka_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 127.0.0.1:5432:5432

  meilisearch:
    image: getmeili/meilisearch:v1.9
    restart: always
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY:-masterKey}
      MEILI_ENV: ${MEILI_ENV:-development}
    volumes:
      - ./data/meili_data:/meili_data
    ports:
      - 127.0.0.1:7700:7700
