services:
  grafana:
    image: grafana/grafana:11.1.3
    restart: always
    ports:
      - 127.0.0.1:3300:3000
    volumes:
      - grafana_data:/var/lib/grafana

  prometheus:
    image: prom/prometheus:v2.53.1
    restart: always
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - prom_data:/prometheus
      - ./conf/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

volumes:
  grafana_data:
  prom_data:
