services:
    plausible_db:
        # Plausible v2.1.1 was tested against PostgreSQL versions 15 and 16
        # https://github.com/plausible/analytics/blob/v2.1.1/.github/workflows/elixir.yml#L21-L32
        image: postgres:16.3-alpine3.20
        restart: always
        volumes:
            - db-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=postgres

    plausible_events_db:
        image: clickhouse/clickhouse-server:24.3.3.102-alpine
        restart: always
        volumes:
            - event-data:/var/lib/clickhouse
            - event-logs:/var/log/clickhouse-server
            - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
            - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
        ulimits:
            nofile:
                soft: 262144
                hard: 262144

    plausible:
        image: ghcr.io/plausible/community-edition:v2.1.1
        restart: always
        command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
        depends_on:
            - plausible_db
            - plausible_events_db
        ports:
            - 8000:8000
        env_file:
            - plausible-conf.env

volumes:
    db-data:
        driver: local
    event-data:
        driver: local
    event-logs:
        driver: local
